name: workout
description: A new Flutter application.

publish_to: "none"

version: 3.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio:
  cached_network_image: ^3.0.0
  carousel_slider: ^3.0.0
  circular_countdown_timer: ^0.2.0
  cloud_firestore: ^1.0.2
  cupertino_icons: ^0.1.3
  firebase_core: ^1.0.2
  flutter_screenutil: ^4.0.4
  flutter_webview_plugin: ^0.3.11
  flutter_staggered_grid_view: ^0.4.0
  get: ^3.26.0
  google_fonts: ^2.0.0
  http: ^0.13.3
  youtube_player_flutter: any

dev_dependencies:
  lint: ^1.0.0
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: 3.5.1

flutter:
  uses-material-design: true

  assets:
    - assets/splash_screen/
    - assets/logo2.png
    - assets/sound/
